image: Visual Studio 2017

before_build:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet tool install -g coveralls.net

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet run --project src\Testeroid\ -- --exclude "[*]coverlet.*" --exclude-path coverlet --exclude-path fixtures --no-build
  - ps: csmacnz.Coveralls --opencover -i C:\projects\testeroid\coverage\coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID

deploy: off
